# Generated by Django 3.2.9 on 2022-01-08 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailstorage',
            name='messages_json',
        ),
        migrations.AddField(
            model_name='emailstorage',
            name='expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emailstorage',
            name='parsed_emails',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emailstorage',
            name='raw_emails',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emailstorage',
            name='user_email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
