# Generated by Django 3.2.11 on 2022-01-09 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20220107_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailstorage',
            name='user_email',
            field=models.EmailField(editable=False, max_length=254, unique=True),
        ),
    ]
