# Generated by Django 3.2.11 on 2022-01-09 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_alter_emailstorage_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailstorage',
            name='parse_status',
            field=models.CharField(choices=[('ns', 'Not Started'), ('ip', 'In Progress'), ('cp', 'Complete')], default='ns', max_length=2),
        ),
    ]
