# Generated by Django 3.2.11 on 2022-01-15 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_emailstorage_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailstorage',
            name='raw_emails_retrieval_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
