# Generated by Django 3.2.11 on 2022-01-23 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_results', '0010_remove_duplicate_indices'),
        ('data', '0007_auto_20220123_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailstorage',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_celery_results.taskresult'),
        ),
    ]
